-- Manual schema changes required because spring.jpa.hibernate.ddl-auto=none.
-- Run as the application schema owner before using notifications and general ledger features.

CREATE TABLE notification (
    notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_email VARCHAR2(100),
    subject VARCHAR2(150) NOT NULL,
    message VARCHAR2(1000) NOT NULL,
    status VARCHAR2(30) NOT NULL,
    source_type VARCHAR2(50),
    source_id NUMBER,
    created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    sent_date TIMESTAMP
);

CREATE INDEX ix_notification_source ON notification(source_type, source_id);
CREATE INDEX ix_notification_status ON notification(status);

CREATE TABLE generalledgerentry (
    ledger_entry_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_code VARCHAR2(30) NOT NULL,
    account_name VARCHAR2(100) NOT NULL,
    debit_amount NUMBER(12,2) DEFAULT 0 NOT NULL,
    credit_amount NUMBER(12,2) DEFAULT 0 NOT NULL,
    entry_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    source_table VARCHAR2(100),
    source_id NUMBER,
    description VARCHAR2(255),
    CONSTRAINT ck_gl_debit_credit_nonnegative
        CHECK (debit_amount >= 0 AND credit_amount >= 0),
    CONSTRAINT ck_gl_one_side
        CHECK (
            (debit_amount > 0 AND credit_amount = 0)
            OR (debit_amount = 0 AND credit_amount > 0)
        )
);

CREATE INDEX ix_gl_source ON generalledgerentry(source_table, source_id);
CREATE INDEX ix_gl_account ON generalledgerentry(account_code);
CREATE INDEX ix_gl_entry_date ON generalledgerentry(entry_date);
